# site settings
title: Joshua Cho
subtitle:
email: joshuasrcho@gmail.com
description: Roboticist | Software Engineer | Maker
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Joshua Cho
street_address:
city: Los Angeles
state: CA
zip_code: 90621
country: United States of America
phone: (714) 906-4147

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 10

# social settings
500px_url:
facebook_url:
github_url: https://github.com/joshuasrcho
linkedin_url: https://www.linkedin.com/in/chojoshua

# build settings
markdown: kramdown

sass:
  style: compressed
